### ISSUE TITLE
The Sample App is not working for me

### ISSUE THREAD

**Issue by alfredmack** [GleasonK/pubnub-android-lolli-chat#1]
i have tried to change publish key and subscribe key but no message is received to other user,and all message are deleted on closing app

**Comment by GleasonK** [comment]
Just noticing this too, thank you. Will look into it tonight and update the code accordingly.

**Comment by alfredmack** [comment]
Thank you,let me know when you fix it ASAP,I want to use pubnub in my new
app

**Comment by GleasonK** [comment]
Alright, appears to be working for me again. The issue was some faulty JSON was sent on the channel by someone forking my project and using my keys. This being only a demo I forgot to check for proper JSON values. For example, the following `chatTime` value was causing some issues:

INVALID: `{"data":{"chatUser":"nicolas:","chatMsg":"Hi","chatTime":"04:09 PM"}}`

VALID: `{"data":{"chatUser":"Kevin","chatMsg":"hey","chatTime":1449788514831}}`

My application parses the chat time using java's `System.currentTimeMillis()`. The invalid JSON was causing a background thread to crash when trying to parse `04:09 PM` as a long. I have added some error catching to the demo, feel free to check out my latest commits. I handled them silently as seen below. If a value couldn't be parsed, it was skipped.

```
for (int i = 0; i < messages.length(); i++) {
    try {
        if (!messages.getJSONObject(i).has("data")) continue;
        JSONObject jsonMsg = messages.getJSONObject(i).getJSONObject("data");
        String name = jsonMsg.getString(Constants.JSON_USER);
        String msg = jsonMsg.getString(Constants.JSON_MSG);
        long time = jsonMsg.getLong(Constants.JSON_TIME);
        ChatMessage chatMsg = new ChatMessage(name, msg, time);
        chatMsgs.add(chatMsg);
    } catch (JSONException e) { // Handle errors silently
        Log.d("History", "JSONException");
    }
}
```

All is well again. Let me know if you still have issues.
